[client]
showSidebarNavigation = false

[theme]
base = "light"

# primary green -- for active elements like buttons, highlights, links
primaryColor = "#2E7D32"

# main background
backgroundColor = "#F8F9FA"

# sidebar background
secondaryBackgroundColor = "#E9F5ED"

# text color -- generic, readable
textColor = "#2E2E2E"

# border color --for inputs, cards
borderColor = "#D0E9D4"

# link color
linkColor = "#388E3C"
